[package]
name = "flv-future-aio"
version = "3.0.0"
edition = "2018"
authors = ["fluvio.io"]
description = "I/O futures for Fluvio project"
repository = "https://github.com/infinyon/flv-future"
license = "Apache-2.0"

[features]
fixture = ["async-test-derive"]
task = ["async-std/default"]
task_unstable = ["task","async-std/unstable"]
net = ["futures-lite","async-net"]
tls = ["net","rustls","webpki","async-tls"]
timer = ["async-io"]
fs = ["async-fs","futures-lite"]
zero_copy = ["nix","task"]
mmap = ["fs","memmap"]

[dependencies]
futures-lite = { version = "1.7.0", optional =  true }
futures-timer = { version = "2.0.2", optional = true }
async-std = { version = "1.6.0", default-features = false, optional = true }
async-io = { version = "1.1.2", optional = true }
async-fs = { version = "1.3.0", optional =  true }
async-net = { version = "1.3.0", optional =  true }
pin-utils = { version = "0.1.0", optional = true }
pin-project = { version = "0.4.0", optional = true }
nix = { version = "0.17.0", optional = true }
bytes = { version = "0.5.0", optional = true }
memmap = { version = "0.7.0", optional = true }
async-trait = { version = "0.1.40", optional = true }
rustls = { version = "0.18.0", features = ["dangerous_configuration"], optional = true }
webpki = { version = "0.21", optional = true }
async-tls = {  version = "0.10.0", optional = true }
async-test-derive = { path = "async-test-derive", version = "1.0.0", optional = true }
flv-util = { version = "0.4.0" }


[dev-dependencies]
lazy_static = "1.2.0"
num_cpus =  "1.10.1"
futures_codec = "0.3.4"
futures-util = "0.3.5"
async-lock = "1.1.0"
tokio-util = { version = "0.3.1", features = ["codec","compat"]} 
flv-util = { version = "0.4.0", features= ["fixture"]}
async-test-derive = { path = "async-test-derive", version = "1.0.0" }
flv-future-aio = { path = ".", features = ["net"] }

