[package]
name = "fluvio-future"
version = "0.1.0"
edition = "2018"
authors = ["fluvio.io"]
description = "I/O futures for Fluvio project"
repository = "https://github.com/infinyon/flv-future"
license = "Apache-2.0"

[features]
task = ["async-std/default", "timer"]
subscriber = ["tracing-subscriber"]
fixture = ["subscriber", "task", "async-test-derive"]
task_unstable = ["task", "async-std/unstable"]
io = ["async-std/default"]
net = ["futures-lite", "async-net", "async-trait"]
tls = ["net", "rustls", "webpki", "async-tls", "pin-project"]
timer = ["async-io"]
fs = ["async-fs", "futures-lite", "pin-utils"]
zero_copy = ["nix", "task_unstable"]
mmap = ["fs", "memmap", "task_unstable"]

[dependencies]
log = "0.4.0"
futures-lite = { version = "1.7.0", optional = true }
futures-timer = { version = "2.0.2", optional = true }
async-std = { version = "1.6.0", default-features = false, optional = true }
async-io = { version = "1.1.2", optional = true }
async-fs = { version = "1.3.0", optional = true }
async-net = { version = "1.3.0", optional = true }
pin-utils = { version = "0.1.0", optional = true }
pin-project = { version = "0.4.0", optional = true }
tracing = { version = "0.1.0" }
tracing-subscriber = { version = "0.2.0", optional = true }
nix = { version = "0.17.0", optional = true }
bytes = { version = "0.5.0", optional = true }
memmap = { version = "0.7.0", optional = true }
async-trait = { version = "0.1.40", optional = true }
rustls = { version = "0.18.0", features = ["dangerous_configuration"], optional = true }
webpki = { version = "0.21", optional = true }
async-tls = { version = "0.10.0", optional = true }
async-test-derive = { path = "async-test-derive", version = "1.0.0", optional = true }


[dev-dependencies]
bytes = "0.5.6"
lazy_static = "1.2.0"
num_cpus = "1.10.1"
futures-util = { version = "0.3.5", features = ["sink"] }
async-lock = "1.1.0"
tokio-util = { version = "0.3.1", features = ["codec", "compat"] }
flv-util = { version = "0.5.0", features = ["fixture"] }
async-test-derive = { path = "async-test-derive", version = "1.0.0" }
fluvio-future = { path = ".", features = ["net", "fixture", "timer", "fs"] }
